#include<iostream>
#include<string>

using namespace std;

#include"Classes.h"
#include"Functions.h"

int main()
{
	cout << "\t\t\t\t\tAt first, let`s check our constructor\n\n\n" << endl;
	Admin one;
	Computer computer;
	one.get_name();
	cout << endl;
	one.get_hour();
	cout << endl;
	one.get_start_time();
	cout << endl;
	one.get_finish_time();
	cout << endl;
	one.get_pay_hour();
	cout << endl;
	one.get_pay();
	cout << endl;
	one.get_information();
	cout << endl;
	cout << endl;
	Admin two("Oleksii Popov", 6, 50, 12, 18, 300);
	two.get_name();
	cout << endl;
	two.get_hour();
	cout << endl;
	two.get_start_time();
	cout << endl;
	two.get_finish_time();
	cout << endl;
	two.get_pay_hour();
	cout << endl;
	two.get_pay();
	cout << endl;
	two.get_information();
	cout << endl;
	cout << endl;
	Admin three(one);
	three.get_name();
	cout << endl;
	three.get_hour();
	cout << endl;
	three.get_start_time();
	cout << endl;
	three.get_finish_time();
	cout << endl;
	three.get_pay_hour();
	cout << endl;
	three.get_pay();
	cout << endl;
	three.get_information();
	cout << endl;
	cout << endl;
	Player ones;
	ones.get_name();
	cout << endl;
	ones.get_telephone();
	cout << endl;
	Player twos("Stas Mihajlov", 947236811);
	twos.get_name();
	cout << endl;
	twos.get_telephone();
	cout << endl;
	Player threes(ones);
	threes.get_name();
	cout << endl;
	threes.get_telephone();
	one.~Admin();
	two.~Admin();
	three.~Admin();
	ones.~Player();
	twos.~Player();
	threes.~Player();
	cout << endl << endl << endl;
	cout << "\t\t\t\t\tOkay, we have tested our constructors. Let's execute the code" << endl << endl;
	Admin admin;
	Player* player = new Player;;
	cout << endl;
	player->set_name();
	cout << endl;
	player->set_telephone();
	cout << endl;
	admin.get_name();
	cout << endl;
	player->get_name();
	cout << endl;
	player->get_telephone();
	cout << endl;
	admin.set_start_time();
	cout << endl << "Your start time is " << admin.get_start_time() << ":00" << endl;
	admin.price_list();
	cout << endl << "How much time you will be playing? ";
	admin.set_hour();
	cout << endl;
	admin.get_information();
	cout << endl;
	player->check();
	cout << endl;
	admin.end();
	cout << endl;
	Player* fourth = new Player;
	fourth->set_name();
	cout << endl;
	fourth->set_telephone();
	Admin four;
	cout << endl;
	four.get_name();
	cout << endl;
	fourth->get_name();
	cout << endl;
	fourth->get_telephone();
	cout << endl;
	four.set_start_time();
	cout << endl << "Your start time is " << four.get_start_time() << ":00" << endl;
	four.price_list();
	cout << endl << "How much time you will be playing? ";
	four.set_hour();
	cout << endl;
	four.get_information();
	cout << endl;
	fourth->check();
	cout << endl;
	four.end();
	Player *fifth = new Player;
	fifth = fourth;
	cout << "Let`s try our operator: \n";
	fifth->get_name();
	fifth->get_telephone();
	cout << endl;
	cout << "Let`s output the object: \n" << *player << "\n\n";
	fifth->turn_off_game();
	fifth->turn_off_computer();
	system("pause");
	cin.get();
	return 0;
}